const data = [
  {
    id: 1,
    calories: 250,
    protein: 15,
    carbs: 200,
    name: "Grilled Chicken",
    portion: 150.0,
    servings: 1,
  },
  {
    id: 2,
    calories: 350,
    protein: 30,
    carbs: 250,
    name: "Baked Salmon",
    portion: 180.0,
    servings: 1,
  },
  {
    id: 3,
    calories: 200,
    protein: 10,
    carbs: 150,
    name: "Scrambled Eggs",
    portion: 120.0,
    servings: 1,
  },
  {
    id: 4,
    calories: 300,
    protein: 25,
    carbs: 220,
    name: "Grilled Steak",
    portion: 200.0,
    servings: 1,
  },
  {
    id: 5,
    calories: 180,
    protein: 8,
    carbs: 120,
    name: "Steamed Broccoli",
    portion: 150.0,
    servings: 1,
  },
  {
    id: 6,
    calories: 400,
    protein: 35,
    carbs: 50,
    name: "Grilled Shrimp",
    portion: 180.0,
    servings: 1,
  },
  {
    id: 7,
    calories: 250,
    protein: 20,
    carbs: 180,
    name: "Tofu Stir-fry",
    portion: 150.0,
    servings: 1,
  },
  {
    id: 8,
    calories: 500,
    protein: 40,
    carbs: 100,
    name: "Chicken Breast with Quinoa",
    portion: 200.0,
    servings: 1,
  },
  {
    id: 9,
    calories: 150,
    protein: 10,
    carbs: 100,
    name: "Greek Yogurt",
    portion: 150.0,
    servings: 1,
  },
  {
    id: 10,
    calories: 300,
    protein: 18,
    carbs: 230,
    name: "Pasta with Pesto",
    portion: 180.0,
    servings: 1,
  },
  {
    id: 11,
    calories: 280,
    protein: 22,
    carbs: 170,
    name: "Beef Stir-fry",
    portion: 180.0,
    servings: 1,
  },
  {
    id: 12,
    calories: 220,
    protein: 15,
    carbs: 180,
    name: "Grilled Pork Chops",
    portion: 160.0,
    servings: 1,
  },
];

export default data;
